### ISSUE TITLE
White Paper

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks-website#1]
For the time being, please change any reference to "White Papers" (plural) to "White Paper" and remove the links to the two later white papers.

Keep the white paper called "Faster, Richer, Fully Customizable..." and remove the other two. We will add them back later, but I want to release them separately to gain the maximum exposure for each.

**Comment by vidalem** [comment]
Done!

**Comment by tjayrush** [comment]
Thanks.
