### ISSUE TITLE
When I tweet mentioning the website, the tweeted image looks weird

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks-website#14]
I tweeted here https://twitter.com/quickblocks/status/924023620426436608 with the following result:

<img width="590" alt="screen shot 2017-10-27 at 5 53 44 pm" src="https://user-images.githubusercontent.com/5417918/32126667-f2ea2a46-bb3f-11e7-938a-493ed2fe90c2.png">

It looks like we can configure something on the website that will make a tweet referencing the site look better. Maybe there's a missing icon or something?

**Comment by vidalem** [comment]
Hi Thomas, check now.
I did change what is called "Twitter card"  
![image](https://user-images.githubusercontent.com/32196559/32128242-86164d9a-bb7c-11e7-9075-9bbfc682b911.png)


I can already see your tweet correctly in my twitter feed 
![image](https://user-images.githubusercontent.com/32196559/32128281-d484f6de-bb7c-11e7-8010-8e65c7bc9099.png)

**Comment by tjayrush** [comment]
Looks good. Closing.
