### ISSUE TITLE
Remove the (R) on the home screen next to large word "QuickBlocks"

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks-website#2]
It doesn't look right to me, and QuickBlocks is marked elsewhere on the site, so I think it's okay to remove the (R) here.

**Comment by tjayrush** [comment]
Also - please make the font for "Accounting for the Revolution" slightly larger. It's hard to see.

**Comment by vidalem** [comment]
Done!
