### ISSUE TITLE
In section QuickBlocks Features

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks-website#3]
- [x] Remove period after "Auto generated data parsing code."

- [x] Insert dash between "Auto" and "generated" in "Auto generated data parsing code" (Should be "Auto-generated data parsing code."

- [x] Change the header "Token Accounting" to "Tokenomics(r)" (This is also a registered trademark.)

- [x] "Parsed to your your smart contract" should be "Parsed to your ~~your~~ smart contract".

**Comment by vidalem** [comment]
Done!

**Comment by tjayrush** [comment]
Thanks. Closing.
