### ISSUE TITLE
Form in "Keep in touch" section has errors in the message

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks-website#4]
The message one gets when one sends an email says:

> Almost done! Now you will receive a confirmation email , please go to your inbox and confirm your suscription. If not received check you spam tray

Changes:

1. Change "Now you will..." to "You will..."
2. Add a period after "...confirmation email" instead of a comma and capitalize "please"
3. Spelling: `suscription` should be `subscription`
4. Should be " If not received check ~~you~~ your spam tray"

**Comment by vidalem** [comment]
Fixed

**Comment by tjayrush** [comment]
Thank you.
