### ISSUE TITLE
If not difficult, remove 'quickblocks.io developed on wordpress from very bottom of site

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks-website#6]
If this is easy to remove, please do so.

If not, don't worry about it, but perhaps we can change the name of the template? It's confusing to have the template for the wordpress site be the name of the company. If we can't remove it, can we rename the template to 'vidal style developed on wordpress"? or something like that?

**Comment by vidalem** [comment]
I only left "QuickBlocks ®" string, check if it fits your needs

**Comment by tjayrush** [comment]
I think I'd like to simply have the text removed and leave the dark blue line at the bottom.  At some distant point in the future we can put some sort of "famous saying" or "wisdom from decentralized land" quotes there (centered, non-scrolling). For now, just remove the text, but leave the dark blue section.

**Comment by vidalem** [comment]
empty footer bottom section done

**Comment by tjayrush** [comment]
Perfect. Thanks.
